### ISSUE TITLE
LAION-400M download/location

### ISSUE THREAD

**Issue by iamsabhoho** [zilliztech/VectorDBBench#193]
Hello! I recently started playing around with the Vector DB Benchmarking platform and it is fascinating! I was especially interested in the LAION-400M dataset and was wondering where I can download it and do my own testing. Thank you in advance!

**Comment by zhuwenxing** [comment]
The raw data is from https://the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-multi/img_emb/

**Comment by iamsabhoho** [comment]
Thank you! I was able to download the embeddings. I have a few more questions if you could help me out that'd be awesome.

1. How did you split the train and test sets? If you could point me to a code file that'd be useful!
2. For the Cohere dataset, I only found the raw data on the provided link. How did you generate the embeddings of 768 dimensions?
3. How can I run the vector database on my own systems? Specifically running Weaviate on our own server. 

Thank you so much!

**Comment by zhuwenxing** [comment]
> How did you split the train and test sets? If you could point me to a code file that'd be useful!

It depends on you. You need to choose what size of your train and test, just make sure they have no intersection.


>For the Cohere dataset, I only found the raw data on the provided link. How did you generate the embeddings of 768 dimensions?

https://huggingface.co/datasets/Cohere/wikipedia-22-12-simple-embeddings

>How can I run the vector database on my own systems? Specifically running Weaviate on our own server.

It depends on whether Weaviate Cloud behaves the same as Weaviate Oss. If not, you need add a client for it, refer to https://github.com/zilliztech/VectorDBBench/blob/main/README.md#adding-new-clients

**Comment by iamsabhoho** [comment]
Hello, I was wondering how I can run with local docker? I have followed the "add new client" section and created a new client so far, but wanted to run it locally with docker. Thank you!
