### ISSUE TITLE
Failed to run test case due to "Parquet magic bytes not found in footer"

### ISSUE THREAD

**Issue by longma8520** [zilliztech/VectorDBBench#199]
I used the local build and the build on pip, and both encountered the following errors:
`pyarrow.lib.ArrowInvalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`

OS: 
MacOS Big Sur
11.7

Steps:
1. Run Your Test
2. Choose QdrantCloud
3. Fill url and api_key
4. Select dataset (Search Performance Test (1M Dataset, 768 Dim)
5. Run your test

**Comment by liliu-z** [comment]
@XuanYang-cn can you help take a look? Thanks!

**Comment by longma8520** [comment]
Looks like my dataset files are broken, I deleted all the datasets, and download them again, the problem is no longer exists
