### ISSUE TITLE
Comparison of precisions and index times is lacking

### ISSUE THREAD

**Issue by lqhl** [zilliztech/VectorDBBench#200]
For vector databases and vector index algorithms, precisions and index times are also very important.

1. It is unfair to compare the QPS (Queries Per Second) of two vector databases if they cannot achieve similar levels of precision. To provide a clearer comparison, you could consider including a figure that shows precision versus QPS, such as those found in [qdrant's benchmark](https://qdrant.tech/benchmarks/) or [ann-benchmarks](https://ann-benchmarks.com/).

<img width="1127" alt="image" src="https://github.com/zilliztech/VectorDBBench/assets/688173/d7e45c7a-107b-437f-af95-d006a2e78600">

2. The exact time of indexing for each experiment is not provided. However, it is crucial for users to know when their vectors are ready for searching. It should be noted that certain graph algorithms (such as HNSW/DiskANN) have a high query per second (QPS) rate but may be slow in the indexing process. Such figure will be helpful:

<img width="1117" alt="image" src="https://github.com/zilliztech/VectorDBBench/assets/688173/0515cf07-badc-45ad-928f-ef84f74c2c18">

**Comment by liliu-z** [comment]
Hi @lqhl,
Thank you for your suggestions.

1. It's possible you may not have had the opportunity to thoroughly examine our benchmark. We have included the build time and recall for each system under test cases in our results. Could you give it a try, and please let us know if you encounter any bugs or UI issues that make these aspects challenging to notice.

2. With respect to recall vs QPS, your idea is indeed correct. However, several reasons have guided us to our current approach:

    1. We are not solely benchmarking open-source systems; we are also focusing on cloud services. Some of these services, such as Zilliz and Pinecone, don't allow users to customize their parameters to tune the recall, aiming to simplify their usage. Consequently, creating a recall vs QPS graph is not feasible. Also this benchmark allow users to customize their parameters for systems allowing tuning to get their own result to do comparison. 

    2. There already exists a number of benchmarks doing what you've suggested, which target individuals with ANN search backgrounds. Our goal is to make this benchmark as straightforward as possible and to assist people who lack understanding about the inner workings of each system.

    3. Concerning reproducibility, generating a recall vs QPS graph that you mentioned, would require conducting a multitude of tests to obtain enough data points, which considerably reduces reproducibility.

3. As for the benchmark graph you cited, we attempted but were unable to reproduce it locally. And might be due to the reproducibility issues I previously mentioned, we've noticed that there hasn't been any update on this graph for quite a while, even though all systems continue to update daily.

**Comment by lqhl** [comment]
Hi @liliu-z . Thank you for your quick reply.

>  1. It's possible you may not have had the opportunity to thoroughly examine our benchmark. We have included the build time and recall for each system under test cases in our results. Could you give it a try, and please let us know if you encounter any bugs or UI issues that make these aspects challenging to notice.

I can only find QPS/QP$/Latency in https://zilliz.com/benchmark. Did I overlook anything?

<img width="1863" alt="image" src="https://github.com/zilliztech/VectorDBBench/assets/688173/5397d28e-01bb-4380-841a-966e883a4b33">

> 2. With respect to recall vs QPS, your idea is indeed correct. However, several reasons have guided us to our current approach:

I understand your decision not to include a recall vs QPS graph. However, it would be helpful if you could annotate the recall and parameters used for each cloud database on each QPS point to enhance clarity.

**Comment by liliu-z** [comment]
> Hi @liliu-z . Thank you for your quick reply.
> 
> > 1. It's possible you may not have had the opportunity to thoroughly examine our benchmark. We have included the build time and recall for each system under test cases in our results. Could you give it a try, and please let us know if you encounter any bugs or UI issues that make these aspects challenging to notice.
> 
> I can only find QPS/QP$/Latency in https://zilliz.com/benchmark. Did I overlook anything?
> 
> <img alt="image" width="1863" src="https://user-images.githubusercontent.com/688173/254759587-5397d28e-01bb-4380-841a-966e883a4b33.png">
> > 2. With respect to recall vs QPS, your idea is indeed correct. However, several reasons have guided us to our current approach:
> 
> I understand your decision not to include a recall vs QPS graph. However, it would be helpful if you could annotate the recall and parameters used for each cloud database on each QPS point to enhance clarity.

Oh, I see. My apologies for the misunderstanding and we definitely need to make this clearer.

The page you referred to is a `Leaderboard`, not the benchmark result itself. When using our benchmark, whether you're checking the standard pre-tested results or conducting your own tests, we display everything, as shown here:
<img width="690" alt="截屏2023-07-20 下午1 09 31" src="https://github.com/zilliztech/VectorDBBench/assets/105927039/00fc2d0e-015b-47be-99b5-bc50d95d5914">

The `Leaderboard` merely scores systems based on QPS derived from test cases. Our goal is to provide users with a quick evaluation without having to delve into detailed benchmark results on a case-by-case basis. However, I couldn't agree more that recall is an essential aspect of performance. And the [scoring rule](https://github.com/zilliztech/VectorDBBench#scoring-rules) right now doesn't consider recall. We will aim to adjust our scoring strategies in the next version to take recall into account. Thank you so much for your suggestions and explanation.

**Comment by lqhl** [comment]
@liliu-z I understand. Thank you.

**Comment by liliu-z** [comment]
If you don't mind I will keep this issue open until we upgrade the scoring strategy

**Comment by lqhl** [comment]
> If you don't mind I will keep this issue open until we upgrade the scoring strategy

Great! I'm looking forward to the new version.
