### ISSUE TITLE
can VectorDBBench run on a k8s cluster?

### ISSUE THREAD

**Issue by yanxiaoqi932** [zilliztech/VectorDBBench#203]
can VectorDBBench run on a k8s cluster? or can only run standalone?

**Comment by liliu-z** [comment]
It can run anywhere, but we didn't prepare a docker image for it so you need to set environment yourself.

**Comment by nelsonspbr** [comment]
Perhaps related (sorry if not) — but can it leverage multi-node setups? For instance, a multi-node Milvus setup with a functional Kubernetes deployment.

**Comment by liliu-z** [comment]
> Perhaps related (sorry if not) — but can it leverage multi-node setups? For instance, a multi-node Milvus setup with a functional Kubernetes deployment.

Hi @nelsonspbr This benchmark is just responsible for querying a Vector Database including Milvus, and it doesn't matter how we deploy Milvus, since all VectorDBBench need is a URL.

**Comment by yanxiaoqi932** [comment]
OK, get it. I'll try it in my spare time.
