### ISSUE TITLE
where can I find the detailed result of openai embedding?

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/VectorDBBench#209]
Hi All,
Where can I get result of openAI on different products?
The leaderboard seems to only support Q1-Q6

**Comment by liliu-z** [comment]
> Hi All, Where can I get result of openAI on different products? The leaderboard seems to only support Q1-Q6

We can see the result in this benchmark's UI by hosting it locally.

The leaderboard's update is asynchronous with this, and depends on the update frequency of the front-end server.

**Comment by liliu-z** [comment]
openAI' 1536 dim is formally supported in the latest version of VectorDBBench
