### ISSUE TITLE
Review of blog-post using VectorDBBench as testing platform

### ISSUE THREAD

**Issue by s-gruneberg** [zilliztech/VectorDBBench#212]
We used this  project for some quick open-source database testing, and wanted to give y'all the opportunity to review the blog-post before we publish it. A preview can be found here:

https://deploy-preview-1--tubular-chimera-571ed3.netlify.app/blog/vector-benchmarking

Feel free to close this issue, or give any feedback, comments, or things you would like incorporated in the blog post. Thanks for your work on this project, we found it really useful!

**Comment by liliu-z** [comment]
> We used this project for some quick open-source database testing, and wanted to give y'all the opportunity to review the blog-post before we publish it. A preview can be found here:
> 
> https://deploy-preview-1--tubular-chimera-571ed3.netlify.app/blog/vector-benchmarking
> 
> Feel free to close this issue, or give any feedback, comments, or things you would like incorporated in the blog post. Thanks for your work on this project, we found it really useful!

Thanks for noticing and this blog is amazing. And just want to let you know that we have already released 1536 dim datasets since yesterday😄. And PgVector is tested.

Also, FYI we created a leaderboard with a scoring logic to assign an individual score to each system crossing all cases. In case you need it.

Plz let us know if anything we can help on this

**Comment by liliu-z** [comment]
@s-gruneberg BTW, people always concern that why VectorDBBench doesn't show a recall-performance graph like ANN-benchmark does. And some explanation about this is necessary to make it more convincing. 
FYI, my idea is here https://github.com/zilliztech/VectorDBBench/issues/200#issuecomment-1643029444

**Comment by liliu-z** [comment]
> > > We used this project for some quick open-source database testing, and wanted to give y'all the opportunity to review the blog-post before we publish it. A preview can be found here:
> > > https://deploy-preview-1--tubular-chimera-571ed3.netlify.app/blog/vector-benchmarking
> > > Feel free to close this issue, or give any feedback, comments, or things you would like incorporated in the blog post. Thanks for your work on this project, we found it really useful!
> > 
> > 
> > Thanks for noticing and this blog is amazing. And just want to let you know that we have already released 1536 dim datasets since yesterday😄. And PgVector is tested.
> > Also, FYI we created a leaderboard with a scoring logic to assign an individual score to each system crossing all cases. In case you need it.
> > Plz let us know if anything we can help on this
> 
> Thanks for checking it out and the kind review. I'll edit it to say that there is now a 1536 dim data-set! @liliu-z One thing we were wondering is if you have a timeline for testing Redis (HNSW) and Chroma on your hardware? I did not create a DBCaseConfig for Redis to switch between IVFFlat/HNSW (but it is a matter of changing "FLAT" to "HNSW" on line 57 in Redis.py).
> 
> Thanks for the quick reply

Thanks for your notice. We don't have a clear time schedule for now, and will definitely try best to make that happen ASAP.
