### ISSUE TITLE
Downloading of Datasets

### ISSUE THREAD

**Issue by ashczq** [zilliztech/VectorDBBench#215]
![image](https://github.com/zilliztech/VectorDBBench/assets/49942750/89427276-57d5-4c7b-8e68-144216211532)

Is there any particular reason why it is taking so long to download? It managed to download the first 2 parts within 20 mins but I cannot continue the downloads even after four hours and there's no progress. Is there a better way to download the datasets?

**Comment by ashczq** [comment]
Just let it run overnight, managed to get the 10M dataset downloaded. Assuming it will take much longer for the 100M Dataset.

**Comment by ashczq** [comment]
Just let it run overnight, managed to get the 10M dataset downloaded. Assuming it will take much longer for the 100M Dataset.

**Comment by liliu-z** [comment]
It takes us ~10 mins to download this 10M dataset. It depends on your bandwidth.
