### ISSUE TITLE
这个东西能搞一个docker版本，打包好的吗？

### ISSUE THREAD

**Issue by UFOXD** [zilliztech/VectorDBBench#216]
这里的依赖包下载遇到了问题，处理起来比较复杂

**Comment by UFOXD** [comment]
真的有蛋疼, mac 上一次安装好了

**Comment by UFOXD** [comment]
> 真的有蛋疼, mac 上一次安装好了

linux装不上

**Comment by liliu-z** [comment]
Can you help paste your error report here so we can better help on this. 
And about docker image, we don't have a plan for now, but will definitely consider this suggestions. 

Thanks!
