### ISSUE TITLE
QPS is very low when searching with filter compared to that with no filter when testing Weaviate

### ISSUE THREAD

**Issue by YJGit** [zilliztech/VectorDBBench#218]
I have used the 10M768Dim data and the 5M1536Dim data to test the weaviate server. Under each set of data, I use the default parameters, i.e.. maxConnections of 64, efConstruction of 128, and ef of -1. However, I have found that the QPS is very low when search with filter, no matter of filer 1% or 99%, yet QPS is high when searching without filter. An example result is listed below:

|     | QPS  |
|  ----  | ----  |
| 10M dataset, 768 Dim  |  645.3399 |
| 10M dataset, 768 Dim, Filter 1%  | 0.8153 |
| 10M dataset, 768 Dim, Filter 99%  | 15.933 |

I'd like to know if this is normal or if there's something wrong ?  I also tried to change the ef to improve the QPS, yet the QPS can raised from 15 to about 30 at most. 
I used weaviate 1.21.1 and the weaviate is deployed by docker in a linux server.

**Comment by xiaofan-luan** [comment]
> I have used the 10M768Dim data and the 5M1536Dim data to test the weaviate server. Under each set of data, I use the default parameters, i.e.. maxConnections of 64, efConstruction of 128, and ef of -1. However, I have found that the QPS is very low when search with filter, no matter of filer 1% or 99%, yet QPS is high when searching without filter. An example result is listed below:
> 
> QPS
> 10M dataset, 768 Dim	645.3399
> 10M dataset, 768 Dim, Filter 1%	0.8153
> 10M dataset, 768 Dim, Filter 99%	15.933
> I'd like to know if this is normal or if there's something wrong ? I also tried to change the ef to improve the QPS, yet the QPS can raised from 15 to about 30 at most. I used weaviate 1.21.1 and the weaviate is deployed by docker in a linux server.

I think the test is as is. Whether it's an reasonable result maybe weaviate community can give some reason.

**Comment by YJGit** [comment]
Thanks a lot!
