### ISSUE TITLE
The recall of IVF_FLAT is very low when we perform 99% filter search in milvus

### ISSUE THREAD

**Issue by XiaominZou** [zilliztech/VectorDBBench#225]
hello,
   When we test the performance of IVF_FLAT in milvus, we observe an unexpected recall. Specifically, the recall of CPU IVF_FLAT drops to 53% , and the recall of GPU IVF_FLAT is only 12% (nlist is 2048, nprobe is 64,) , when we perform  99% filter search (OpenAI generated 500K vectors, 1536 dimensions). Could you explain the result?
    Thanks

**Comment by xiaofan-luan** [comment]
the reason is most of the data is filtered, and for IVFFLAT the probed bucket can not find enough result.

We optimized a lot on HNSW, so please try HNSW result.
Another way is to simply increase bucket
