### ISSUE TITLE
Redis config is drastically wrong for benchmarks

### ISSUE THREAD

**Issue by Spartee** [zilliztech/VectorDBBench#228]
The redis configuration doesn't even use the ANN algorithm ``HNSW``. You're comparing Redis KNN to others ANN. Hopefully just an oversight that Redis supports both. 

**please note**: Anyone who comes to this repo and uses the default configs should be aware of this.

**Comment by xiaofan-luan** [comment]
> The redis configuration doesn't even use the ANN algorithm `HNSW`. You're comparing Redis KNN to others ANN. Hopefully just an oversight that Redis supports both.
> 
> **please note**: Anyone who comes to this repo and uses the default configs should be aware of this.

@Spartee 
could you contribute for the right config? we are glad to take contribution and rerun the test

**Comment by xiaofan-luan** [comment]
<img width="642" alt="image" src="https://github.com/zilliztech/VectorDBBench/assets/83447078/abada480-6dc8-430b-a1a8-d58dc7881840">
 
 I think we need to fallback to HNSW?

**Comment by Spartee** [comment]
Happy to. Working on it already. We will do this.
