### ISSUE TITLE
Question about testing on GPU-based Milvus 

### ISSUE THREAD

**Issue by BaiMuDaSanQiao** [zilliztech/VectorDBBench#231]
I am currently working on testing the GPU version of Milvus. I just started using this tool and it seems that I haven't found the testing methods for the GPU version of Milvus. Did I miss something, or is this tool currently not supporting testing for the GPU version of Milvus?

**Comment by liliu-z** [comment]
Yes, we didn't support all indexes for now. Will add it recently!
