### ISSUE TITLE
Can we test performance against dynamic schema search/query?

### ISSUE THREAD

**Issue by nobody4t** [zilliztech/VectorDBBench#236]
We are planing to use Milvus as our vectordb. The usage would be heavy. And dynamic schema should be a must.
But with heavy usage, the perfomrace agaist dynamic schema is one of our concerns.

If possible, it woule be nice to have a benchmark on this.
If this make sense, please share more.

Thanks.

**Comment by xiaofan-luan** [comment]
@nobod4t feel free to add some test and any contribution is welcomed.
I'd foresee performance degrade on some use cases. in Milvus 2.4 we will try to add inverted index on milvus scalar
