### ISSUE TITLE
VectorDBBench configuration and testing

### ISSUE THREAD

**Issue by mybabyiscue** [zilliztech/VectorDBBench#240]
According to the introduction on the official website, python3.11.0 has been configured and the required plug-ins have been installed.

But running init bench directly reports an error. I checked that streamlit is installed. Not sure what the problem is
image

![image](https://github.com/zilliztech/VectorDBBench/assets/96758134/e628ca07-cbfb-47ba-9ad4-647c7cf390b4)

**Comment by mybabyiscue** [comment]
![image](https://github.com/zilliztech/VectorDBBench/assets/96758134/adf67ee0-d834-42b7-a31e-d86446072fb9)

**Comment by alwayslove2013** [comment]
The error here was popped by Chroma's test client.

It seems to be a common problem with Chroma. 
https://docs.trychroma.com/troubleshooting#sqlite
https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300

If your purpose for using `vectordb-bench` does not include testing `chroma`, we recommend that you git clone this repo and then choose to install the relevant dependencies **based on your testing needs.**
```sh
git clone https://github.com/zilliztech/VectorDBBench
cd VectorDBBench
pip install -e ".[pincone, pgvector, redis]"
init_bench
```
![image](https://github.com/zilliztech/VectorDBBench/assets/22510720/3fa1eb97-3ace-46c3-a6f5-e6d390f01e40)
