### ISSUE TITLE
feat: add vector DB `pgvecto.rs`

### ISSUE THREAD

**Issue by cutecutecat** [zilliztech/VectorDBBench#241]
Hello, I am happy to know this Benchmark framework for vector DB, it would be much helpful for vector DB profile form index build to query with/without filter, and enlight the bottleneck of different index type and arguments.

I would like to introduce postgres extension `pgvecto.rs`, which is similar to `pgvector` but coded by `Rust`, with some new features.

repo: https://github.com/tensorchord/pgvecto.rs

I could make a contribution to introduce `pgvecto.rs` into this benchmark toolkit!

**Comment by xiaofan-luan** [comment]
feel free to contribute and wlecome!

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:
