### ISSUE TITLE
Dataset for task dependencies is too slow to download

### ISSUE THREAD

**Issue by dushulin** [zilliztech/VectorDBBench#248]
![image](https://github.com/zilliztech/VectorDBBench/assets/25276301/ba121725-04fc-4a9f-919e-6fb43e597924)
how to speed up dataset download

**Comment by alwayslove2013** [comment]
@dushulin VDBBench now includes a feature to configure data sources, supporting the selection of two sources: `us-west` and `cn-shanghai`. Feel free to give it a try!
pr: #260 #262 
![image](https://github.com/zilliztech/VectorDBBench/assets/22510720/85f89f26-af36-43be-8fce-17bb79c45d85)

**Comment by Kodp** [comment]
still too slow

**Comment by xiaofan-luan** [comment]
@Kodp 
where is your server located?

I believe a CDN might be needed to accelerate download
