### ISSUE TITLE
Ability to Edit Concurrency as well as Time Duration for Tests

### ISSUE THREAD

**Issue by anrahman4** [zilliztech/VectorDBBench#271]
Want to be able to adjust the default time of each concurrent process run from 30 seconds to anytime, as well as statically set the amount of concurrent processes that will run at one time. 

Is this possible by adjusting the files? Or is the init_bench binary precompiled already if installed via pip?

**Comment by anrahman4** [comment]
Nevermind, this can be edited.

For others curious, to edit the concurrency, edit the NUM_CONCURRENCY variable in the following file
/home/<USER>/.local/lib/python3.11/site-packages/vectordb_bench/__init.py__

To edit seconds the test is run for, edit the duration variable in the init function. 
/home/labuser/.local/lib/python3.11/site-packages/vectordb_bench/backend/runner/mp_runner.py

**Comment by alwayslove2013** [comment]
@anrahman4 
Nice sharing~
We will support more flexible configuration settings in the future!
