### ISSUE TITLE
Search Performance Test (100M Dataset, 768 Dim) 数据通过阿里云拉取不到

### ISSUE THREAD

**Issue by renhongchao** [zilliztech/VectorDBBench#275]
![image](https://github.com/zilliztech/VectorDBBench/assets/3937985/7e855f05-2502-45f0-911f-2915893de7b5)
![image](https://github.com/zilliztech/VectorDBBench/assets/3937985/71613b66-f5cf-447e-9f9d-04592e5351dd)

后台日志
 pre run case error: {'status': 404, 'x-oss-request-id': '65D7FC444CD81B3437038CBF', 'details': {'Code': 'NoSuchKey', 'Message': 'The specified key does not exist.', 'RequestId': '65D7FC444CD81B3437038CBF', 'HostId': 'assets.zilliz.com.cn', 'Key': 'benchmark/laion_large_100m/neighbors_tail_1p.parquet', 'EC': '0026-00000001', 'RecommendDoc': 'https://api.aliyun.com/troubleshoot?q=0026-00000001'}} (task_runner.py:92) (1036951)

**Comment by XuanYang-cn** [comment]
related to: #267

**Comment by renhongchao** [comment]
是不准备提供了么，267 issues已经很久了

**Comment by XuanYang-cn** [comment]
@renhongchao will be fixed soon, please use s3 for 100M LAION dataset before the fix :)

**Comment by anrahman4** [comment]
Is there an ETA on when the fix will occur? Want to use this without S3 while testing Milvus

**Comment by kish5430** [comment]
HI Team, could you please release the version that fixes the issue?

**Comment by XuanYang-cn** [comment]
@kish5430 we will release next version at 0.0.7 milestone, before that, you could clone this repository and use the latest code by `pip install -e .`

**Comment by XuanYang-cn** [comment]
0.0.7 release, should be fixed
