### ISSUE TITLE
benchmark test values 0

### ISSUE THREAD

**Issue by dipshirajput** [zilliztech/VectorDBBench#284]
Hi all,
while i was trying to run the test to have a comparison benchmark between Milvus and Qdrant, i am getting all values as 0, 

please let me know for some suggestions. Thanks in advance.
![mil](https://github.com/zilliztech/VectorDBBench/assets/52161957/e906284e-bb20-4a31-a61f-02c456c038c0)

**Comment by alwayslove2013** [comment]
- Regarding the error with `qdrant`, it appears to be a configuration error in the parameters. Could you please check if you are testing `QdrantCloud` or locally deployed?
- As for `milvus`, there is no information related to milvus in the logs here. Could you please rerun it, for example, rerun the case of 768dim1M, and provide us with the log information?

**Comment by dipshirajput** [comment]
Hi @alwayslove2013 , its Milvus versus QuadrantCloud . 
and  i have just used this, https://github.com/zilliztech/VectorDBBench link in order to perform the comparison. do we need to execute anything extra than that ?

**Comment by alwayslove2013** [comment]
@dipshirajput 
- We are trying to solve the `QdrantCloud Client` issue.
- Regarding the `Milvus` error, we need more complete logs, we can't see any milvus error in the screenshot.

**Comment by dipshirajput** [comment]
Hi @alwayslove2013 ,
which step is responsible for running the databases ? i mean if i run init_bench , its unable to connect to the milvus server.

![Screenshot from 2024-03-14 13-01-18](https://github.com/zilliztech/VectorDBBench/assets/52161957/16960169-5e86-49b0-8856-0f3b588191d8)


Please let me know for any suggestions. Thanks.

**Comment by alwayslove2013** [comment]
@dipshirajput You are testing `Laion 100M` data, there are some problems with this case.
The latest 0.0.7 has fixed it, you need to upgrade it first.

Or now you can test Milvus with the `Cohere 768dim 1M` case, a smaller dataset.

**Comment by dipshirajput** [comment]
@alwayslove2013 
with Cohere 768dim 1M, i am still getting the same.
![Screenshot from 2024-03-14 13-48-41](https://github.com/zilliztech/VectorDBBench/assets/52161957/3a30f27b-5d04-4cc7-bf0a-6733b5292125)

**Comment by alwayslove2013** [comment]
@dipshirajput Can you please confirm that you have successfully deployed the milvus service? `VDBBench` is just a test client.

FYI, https://milvus.io/docs/install_standalone-helm.md
