### ISSUE TITLE
 failed to install packages

### ISSUE THREAD

**Issue by ybtsdst** [zilliztech/VectorDBBench#288]
`pip install .` failed to install packages under site-package related directories, but only dist-info.
I find the last commit was a update to toml file. https://github.com/zilliztech/VectorDBBench/commit/9325a5a277b614e820b03384d3db49be2c3b429c

I tried [this](https://stackoverflow.com/a/76739181/6634177) and it works:
```
[tool.setuptools.packages.find]
where = ["."]
include = ["vectordb_bench"]
```

**Comment by XuanYang-cn** [comment]
@ybtsdst nice catch!
