### ISSUE TITLE
Qdrant connector is failing (4/7/24)

### ISSUE THREAD

**Issue by ytang07** [zilliztech/VectorDBBench#298]
![zv5ei718xzsc1](https://github.com/zilliztech/VectorDBBench/assets/17556662/4cbc8ddf-16a5-4fa3-a0eb-0913ea3e18cf)

Qdrant connector is failing

**Comment by ytang07** [comment]
@liliu-z

**Comment by alwayslove2013** [comment]
Fixed.  PR: #300 

You could fetch the **latest code** by `git` and re-run `init_bench`.

If you installed `VectorDBBench` by `PYPI`, sorry that you need to wait for us to release a new version.
