### ISSUE TITLE
ValidationError: 2 validation errors for TaskConfig db_config Can't instantiate abstract class DBConfig with abstract method to_dict (type=type_error) db_case_config instance of DBCaseConfig expected (type=type_error.arbitrary_type; expected_arbitrary_type=DBCaseConfig)

### ISSUE THREAD

**Issue by zhaojianjun0319** [zilliztech/VectorDBBench#299]
ValidationError: 2 validation errors for TaskConfig db_config Can't instantiate abstract class DBConfig with abstract method to_dict (type=type_error) db_case_config instance of DBCaseConfig expected (type=type_error.arbitrary_type; expected_arbitrary_type=DBCaseConfig)

File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/opt/code/vectordb_bench/frontend/pages/run_test.py", line 65, in <module>
    main()
File "/opt/code/vectordb_bench/frontend/pages/run_test.py", line 48, in main
    generate_tasks(activedDbList, dbConfigs, activedCaseList, allCaseConfigs)
File "/opt/code/vectordb_bench/frontend/components/run_test/generateTasks.py", line 8, in generate_tasks
    task = TaskConfig(
           ^^^^^^^^^^^
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__

**Comment by xieydd** [comment]
I meet the same error, and it is random, wired.
```
pydantic.error_wrappers.ValidationError: 2 validation errors for TaskConfig
│ db_config
│   Can't instantiate abstract class DBConfig with abstract method to_dict (type=type_error)
│ db_case_config
│   instance of DBCaseConfig expected (type=type_error.arbitrary_type; expected_arbitrary_type=DBCaseConfig)
│ 2024-06-07 02:19:22.136 Uncaught app exception
│ Traceback (most recent call last):
│   File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
│     exec(code, module.__dict__)
│   File "/opt/code/vectordb_bench/frontend/pages/run_test.py", line 65, in <module>
│     main()
│   File "/opt/code/vectordb_bench/frontend/pages/run_test.py", line 48, in main
│     generate_tasks(activedDbList, dbConfigs, activedCaseList, allCaseConfigs)
│   File "/opt/code/vectordb_bench/frontend/components/run_test/generateTasks.py", line 8, in generate_tasks
│     task = TaskConfig(
│            ^^^^^^^^^^^
│   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
```
![image](https://github.com/zilliztech/VectorDBBench/assets/20329697/85b53aa1-44ca-4e89-971a-ccf2f8f82729)

![image](https://github.com/zilliztech/VectorDBBench/assets/20329697/669355c4-2e9c-4c79-b062-49d5e0a1b63d)
