### ISSUE TITLE
init_bench

### ISSUE THREAD

**Issue by GreateFang** [zilliztech/VectorDBBench#303]
I worked in Centos7.6 and had successfully exec “pip3.11 install vector-bench”
![image](https://github.com/zilliztech/VectorDBBench/assets/32962590/a9edf2c4-9262-4a91-bffb-560fe8edfd97)
IS anything wrong in my operation? by the way I install vector-bench offline

**Comment by alwayslove2013** [comment]
@XuanYang-cn Could you help~

**Comment by GreateFang** [comment]
I  found It was me forgot to set init_bench bin path in env variable $PATH.  Maybe can consider add this in the install readme~
![image](https://github.com/zilliztech/VectorDBBench/assets/32962590/4206e7b2-9718-4767-b0a4-791794921b72)
Thanks for reply!
