### ISSUE TITLE
Recall or Precision

### ISSUE THREAD

**Issue by adbmal** [zilliztech/VectorDBBench#305]
whether Vectordb has precision metrics?
I've noticed that everyone is discussing `recall`, and in VectorDBBench, recall is used as a key metric. After looking into the calculation method of recall in VectorDBBench, I feel it should be referred to as precision. 
https://github.com/zilliztech/VectorDBBench/blob/296683255af8c0ba0b82bf60e96428cfbb58df2f/vectordb_bench/metric.py#L56-L62

https://en.wikipedia.org/wiki/Precision_and_recall

![image](https://github.com/zilliztech/VectorDBBench/assets/2441744/ce5556ec-ae33-42c0-b7db-aad08066c3df)

This issue has been bothering me for quite some time.

**Comment by alwayslove2013** [comment]
@adbmal In fact, for top-k search results, our ground truth also consists of only k items. In this scenario, recall and precision are equal.
