### ISSUE TITLE
查询节点异常重启，集群版本2.3.3   报错如下，哪位能帮忙看下 谢谢

### ISSUE THREAD

**Issue by zhaojianjun0319** [zilliztech/VectorDBBench#306]
[2024/04/18 09:17:35.529 +00:00] [INFO] [segments/segment_loader.go:801] ["there are no delta logs saved with segment, skip loading delete record"] [segmentID=448008565466103170]
SIGILL: illegal instruction
PC=0x7f39ecfdfe71 m=125 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc4 0xe2 0x69 0x99 0x5 0x96 0xe0 0x38 0x0 0xc4 0xc1 0xe2 0x2a 0xce 0xc5 0xf2

goroutine 2080 [syscall, locked to thread]:
non-Go function
	pc=0x7f39ecfdfe71
non-Go function
	pc=0x7f39ecfd948b
non-Go function
	pc=0x7f39ecfdcff4
non-Go function
	pc=0x7f39ecfc4f07
runtime.cgocall(0x3e4e5b0, 0xc001122e10)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc001122de8 sp=0xc001122db0 pc=0x175777c
github.com/milvus-io/milvus/internal/querynodev2/segments._Cfunc_Search(0x7f3909220000, 0x7f3907a12000, 0x7f3907a000c0, {0xc001243cc0, 0xc001243ca8, 0x0, {0x0, 0x0, 0x0, 0x0, ...}}, ...)
	_cgo_gotypes.go:831 +0x55 fp=0xc001122e10 sp=0xc001122de8 pc=0x3c361f5
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Search.func1.1(0x17921c0?, 0xc000066500?, {0xc001243cc0, 0xc001243ca8, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:350 +0xf9 fp=0xc001122e98 sp=0xc001122e10 pc=0x3c43c39
github.com/milvus-io/milvus/internal/querynodev2/segments.(*LocalSegment).Search.func1()
	/go/src/github.com/milvus-io/milvus/internal/querynodev2/segments/segment.go:350 +0x94 fp=0xc001122f28 sp=0xc001122e98 pc=0x3c439f4
github.com/milvus-io/milvus/pkg/util/conc.(*Pool[...]).Submit.func1()
	/go/src/github.com/milvus-io/milvus/pkg/util/conc/pool.go:79 +0xbc fp=0xc001122f88 sp=0xc001122f28 pc=0x3c2557c
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:67 +0x97 fp=0xc001122fe0 sp=0xc001122f88 pc=0x2c75237
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc001122fe8 sp=0xc001122fe0 pc=0x17c89a1
created by github.com/panjf2000/ants/v2.(*goWorker).run
	/go/pkg/mod/github.com/panjf2000/ants/v2@v2.7.2/worker.go:48 +0x65

goroutine 1 [chan receive, 1 minutes]:
runtime.gopark(0xc000bb6100?, 0xc001199790?, 0xfe?, 0x2d?, 0x4185fa0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001cf738 sp=0xc0001cf718 pc=0x17920d6
runtime.chanrecv(0xc00010e9c0, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc0001cf7c8 sp=0xc0001cf738 pc=0x175a5bd
runtime.chanrecv1(0xc001059750?, 0x4c0ed58?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc0001cf7f0 sp=0xc0001cf7c8 pc=0x175a0b8
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0xc001116640)
	/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:388 +0x9a5 fp=0xc0001cfc70 sp=0xc0001cf7f0 pc=0x3d52785
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x10?, {0xc00011a150?, 0x3, 0x3}, 0xc001100120)
	/go/src/github.com/milvus-io/milvus/cmd/milvus/run.go:44 +0x2ab fp=0xc0001cfd40 sp=0xc0001cfc70 pc=0x3d5d6cb
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0xc00011a150?, 0x3, 0x3})
	/go/src/github.com/milvus-io/milvus/cmd/milvus/milvus.go:60 +0x20e fp=0xc0001cfdb8 sp=0xc0001cfd40 pc=0x3d5d38e
main.main()
	/go/src/github.com/milvus-io/milvus/cmd/main.go:95 +0x3c5 fp=0xc0001cff80 sp=0xc0001cfdb8 pc=0x3d61e45
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc0001cffe0 sp=0xc0001cff80 pc=0x1791ca7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001cffe8 sp=0xc0001cffe0 pc=0x17c89a1

goroutine 2 [force gc (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000092fb0 sp=0xc000092f90 pc=0x17920d6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000092fe0 sp=0xc000092fb0 pc=0x1791f10
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000092fe8 sp=0xc000092fe0 pc=0x17c89a1
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x671d301?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000093780 sp=0xc000093760 pc=0x17920d6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000937c8 sp=0xc000093780 pc=0x177a85e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000937e0 sp=0xc0000937c8 pc=0x176f926
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000937e8 sp=0xc0000937e0 pc=0x17c89a1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x6725a40?, 0x731092?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000093f70 sp=0xc000093f50 pc=0x17920d6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x6725a40)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000093fa0 sp=0xc000093f70 pc=0x1778693
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000093fc8 sp=0xc000093fa0 pc=0x1778ca5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000093fe0 sp=0xc000093fc8 pc=0x176f8c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x17c89a1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x480dc58?, 0x0?, 0x20?, 0x1000000010?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000047e28 sp=0xc000047e08 pc=0x17920d6
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc000047fe0 sp=0xc000047e28 pc=0x176e967
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x17c89a1
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 19 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008e750 sp=0xc00008e730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008e7e0 sp=0xc00008e750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008e7e8 sp=0xc00008e7e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle), 1 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004e6750 sp=0xc0004e6730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004e67e0 sp=0xc0004e6750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004e67e8 sp=0xc0004e67e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x6771540?, 0x1?, 0x38?, 0x95?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000094750 sp=0xc000094730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000947e0 sp=0xc000094750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000947e8 sp=0xc0000947e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x6771540?, 0x1?, 0xe2?, 0x9b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008ef50 sp=0xc00008ef30 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008efe0 sp=0xc00008ef50 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008efe8 sp=0xc00008efe0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x6771540?, 0x1?, 0x9f?, 0x28?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008f750 sp=0xc00008f730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008f7e0 sp=0xc00008f750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008f7e8 sp=0xc00008f7e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x112cbac034d51a?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008ff50 sp=0xc00008ff30 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008ffe0 sp=0xc00008ff50 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x112cbac034c315?, 0x3?, 0x10?, 0x17?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000094f50 sp=0xc000094f30 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000094fe0 sp=0xc000094f50 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000094fe8 sp=0xc000094fe0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x112cbadf158c09?, 0x1?, 0xc2?, 0xb5?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000090750 sp=0xc000090730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000907e0 sp=0xc000090750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000907e8 sp=0xc0000907e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 24 [GC worker (idle)]:
runtime.gopark(0x112cbadf1f4d54?, 0x1?, 0xa7?, 0x2b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000090f50 sp=0xc000090f30 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000090fe0 sp=0xc000090f50 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000090fe8 sp=0xc000090fe0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x112cbac034b857?, 0x1?, 0x4a?, 0x63?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000095750 sp=0xc000095730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000957e0 sp=0xc000095750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000957e8 sp=0xc0000957e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 25 [GC worker (idle)]:
runtime.gopark(0x6771540?, 0x1?, 0xe7?, 0xe6?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000091750 sp=0xc000091730 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000917e0 sp=0xc000091750 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000917e8 sp=0xc0000917e0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x112cbadf156db9?, 0x1?, 0x1a?, 0x81?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004e6f50 sp=0xc0004e6f30 pc=0x17920d6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004e6fe0 sp=0xc0004e6f50 pc=0x1771691
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004e6fe8 sp=0xc0004e6fe0 pc=0x17c89a1
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

**Comment by alwayslove2013** [comment]
@zhaojianjun0319 
Please describe clearly:
1. which case of VDBB was tested?
2. the specific cluster configuration of milvus, such as the number of query nodes, and the cpu and memory resources, etc.

**Comment by xiaofan-luan** [comment]
illegal instruction.
Most likely you are testing on a very old server with no AVX support.
We fixed that issue in later 2.3 version. Try 2.3.13 instead see if it works
