### ISSUE TITLE
Why is this keep on failing for Qdrant?

### ISSUE THREAD

**Issue by hsnalee** [zilliztech/VectorDBBench#307]
I am trying to benchmark Qdrant and Milvus but for Qdrant the tool is failing and I don't know why. I have installed the Qdrant and my docker container is also up and running, attaching the SS below. 

![image](https://github.com/zilliztech/VectorDBBench/assets/145953405/1d681438-39ba-4edf-828e-b7e5745a0d29)

![Screenshot 2024-04-21 191837](https://github.com/zilliztech/VectorDBBench/assets/145953405/5a65777b-b9f8-4c70-bba2-8635840cbbf3)

**Comment by RajnandiniG** [comment]
<img width="904" alt="shangai-500k-1%-milvus" src="https://github.com/zilliztech/VectorDBBench/assets/160368396/cc88e92e-180a-4cd4-ad2e-09c610e92474">

Hello, I am also trying to implement this but it keeps on giving me empty results, screenshot is attached!
