### ISSUE TITLE
【PgVectoRS】wrong use of commit

### ISSUE THREAD

**Issue by frg01** [zilliztech/VectorDBBench#327]
https://github.com/zilliztech/VectorDBBench/blob/4b3871237208acb2ffb9db9bef0077b692feb69c/vectordb_bench/backend/clients/pgvecto_rs/pgvecto_rs.py#L189

commit is use in condition that if data change , It's not necessary to use it here after a select sql.

**Comment by alwayslove2013** [comment]
@frg01 Thank you for trying out VDBBench and providing valuable suggestions!

@cutecutecat could you help check it~

**Comment by alwayslove2013** [comment]
@cutecutecat Nice!  Please feel free to reach out if you require further assistance~
