### ISSUE TITLE
【bug】 dataset DIR path should be consistency

### ISSUE THREAD

**Issue by frg01** [zilliztech/VectorDBBench#328]
DATASET_LOCAL_DIR different in container use and local use.

https://github.com/zilliztech/VectorDBBench/blob/4b3871237208acb2ffb9db9bef0077b692feb69c/vectordb_bench/__init__.py#L17

but in local project ,it produce a file, name is .env.example .
![image](https://github.com/zilliztech/VectorDBBench/assets/107344363/b1cd47bf-054b-4e9a-b908-23a6fe6d03fa)

It can be seen that the variable names are the same, but the values ​​are different.
DATASET_LOCAL_DIR = env.path("DATASET_LOCAL_DIR", "/tmp/vectordb_bench/dataset")
DATASET_LOCAL_DIR="/tmp/vector_db_bench/dataset"

one is vectordb_bench ,another is vector_db_bench

**Comment by alwayslove2013** [comment]
@frg01 good catch!
