### ISSUE TITLE
How to test ES performance for physical machine deployments instead of the cloud?

### ISSUE THREAD

**Issue by kelvin-qin** [zilliztech/VectorDBBench#344]
Once I've installed VectorDBBench, I can only select ElasticCloud in the Select Client step, and my locally deployed ES doesn't seem to be able to be tested.

I checked the HELP information but got no direct help.
Please also let me know if I am missing something important, thank you very much.
So, how can I test the local ES cluster deployed on my physical machine?

**Comment by alwayslove2013** [comment]
@kelvin-qin 
At the moment we haven't tested how to connect to a locally deployed ES, maybe some code modifications are needed.

**Comment by xiaofan-luan** [comment]
> @kelvin-qin At the moment we haven't tested how to connect to a locally deployed ES, maybe some code modifications are needed.

you will need to deploy es by yourself and change some connection configs

**Comment by kelvin-qin** [comment]
> > @kelvin-qin At the moment we haven't tested how to connect to a locally deployed ES, maybe some code modifications are needed.
> 
> you will need to deploy es by yourself and change some connection configs

These configs you mentioned should not be directly solved by parameters, is it necessary to modify the source code and compile it?

**Comment by kelvin-qin** [comment]
fine! I found the location of the config code and changing the name in a dict.It took effect!

**Comment by kelvin-qin** [comment]
fine! I found the location of the config code and changing the name in a dict.It took effect!

**Comment by alwayslove2013** [comment]
@kelvin-qin Wonderful! Could you please share the detailed solution? This would be most helpful for assisting others as well.
> fine! I found the location of the config code and changed the name in a dict. It took effect!

**Comment by kelvin-qin** [comment]
Of course. The directory location is `vectordb_bench/backend/clients/elastic_cloud/`, and the one thing that needs to be changed is `config.py`, which changes the dictionary key "cloud_id" to "hosts ". This will allow the user to enter the normal es uri.

This is not elegant, it destroys the original route, at this time and cloud deployment can not be used at the same time, a better way is to determine the form of input to do an if  switch.

Thanks.

**Comment by alwayslove2013** [comment]
@kelvin-qin Thank you so much for sharing your successful experience! It does not seem overly complicated, and I will certainly consider integrating this configuration. I hope that even more users can benefit from it.
