### ISSUE TITLE
How was openAI 5M dataset generated ?

### ISSUE THREAD

**Issue by vaibs001** [zilliztech/VectorDBBench#354]
I have been using the OpenAI 5M dataset. I need the raw source dataset for it and came across https://huggingface.co/datasets/allenai/c4 as mentioned in the readme. However none of the datasets in allenai/c4 have 5M rows in the train dataset, and I found it hard to point the raw source data. Could you please help me with how the OpenAI 5M dataset was generated ? My best guess so far is it is a combination of en and en-multi train and validation datasets.
Thank you.

**Comment by alwayslove2013** [comment]
@zhuwenxing could you help explain the process we used to generate the `OpenAI` dataset?

**Comment by zhuwenxing** [comment]
We sampled 5 million data points from the dataset, but at the time, we only kept the embeddings and didn't preserve the correspondence between the text and embeddings, so we may not be able to provide you with the original text and corresponding embeddings.

**Comment by vaibs001** [comment]
Thanks @zhuwenxing 
The hf dataset has many subsets mostly based on language or blocked words etc. Do you remember 
1) Which data subset was used for sampling ? was it -en, -en.multi or something else ?
2) How was the query set created ? I am assuming it was also chosen from either train or validation data subset, but which ones ?
3) What kind of sampling was done ?

**Comment by zhuwenxing** [comment]
I apologize that I can't provide more definitive answers to these questions. When creating this dataset, I only worked with the embedding files, and the specifics of the data preparation process were not recorded or are not readily available to me now.

Your questions highlight valuable aspects of data provenance that we should capture in future work.
