### ISSUE TITLE
[Question] How was the top-k parameter set in benchmark results?

### ISSUE THREAD

**Issue by reshnah** [zilliztech/VectorDBBench#426]
Hi.
Thanks for providing valuable benchmark tool.

I was to reproduce the benchmark result, and wondered how should I set k parameter to make same environment.
Should I leave k as the default 100, or set certain value?

Thanks.

**Comment by alwayslove2013** [comment]
@reshnah Thank you for using VDBBench! 

You can adjust the value of `k` when running the test, with the default set to `100`. 
We also used `k=100` during testing for the `standard` results.
![image](https://github.com/user-attachments/assets/54c7dcce-60f3-4958-8406-51d3e2edd51c)

**Comment by reshnah** [comment]
Thank you!
